import { useMemo,useState } from 'react';
import { PRODUCT_IDENTITY,type ConcreteProject } from '../domain/project';
import type { MixAnalysis,MixDesign } from '../domain/mixDesign';
import type { DiagnosticSummary } from '../engineering/diagnostics';
import type { PackingResult } from '../engineering/packing';
import type { CompactionState } from '../engineering/compaction';
import { buildAIReviewPrompt } from '../engineering/aiReview';

interface Props{project:ConcreteProject;mix:MixDesign;analysis:MixAnalysis;packing:PackingResult;diagnostics:DiagnosticSummary;compaction:CompactionState;onClose:()=>void;onResult?:()=>void;onReport?:()=>void;}
export function AIReviewPanel(props:Props){
 const payload=useMemo(()=>buildAIReviewPrompt(props.project,props.mix,props.analysis,props.packing,props.diagnostics,props.compaction),[props.project,props.mix,props.analysis,props.packing,props.diagnostics,props.compaction]);
 const[copied,setCopied]=useState<'prompt'|'data'|null>(null);const[expanded,setExpanded]=useState(false);
 const copy=async(kind:'prompt'|'data')=>{await navigator.clipboard.writeText(kind==='prompt'?payload.prompt:payload.compactData);setCopied(kind);window.setTimeout(()=>setCopied(null),1600)};
 return <div className="editor-overlay ai-review-panel" dir="rtl"><div className="editor-header"><div><span className="workflow-kicker">STEP 02 • ENGINEERING DECISION FLOW</span><b>Engineering Copilot طلوع</b><span>پرونده تصمیم‌یار فارسی بر پایه طرح اختلاط و خروجی شبیه‌سازی</span></div><button className="panel-close" onClick={props.onClose}>×</button></div>
 <nav className="decision-flow-nav" aria-label="مسیر تصمیم مهندسی"><button onClick={props.onResult}>01 نتیجه</button><span>←</span><button className="active">02 Copilot</button><span>←</span><button disabled={!payload.ready} onClick={props.onReport}>03 گزارش</button><span>←</span><b>04 Trial Mix</b></nav>
 <div className={`ai-ready-banner ${payload.ready?'ready':'waiting'}`}><div><b>{payload.ready?'✓ پرونده مهندسی آماده تحلیل Copilot است':'◌ ابتدا شبیه‌سازی را تا پایان اجرا کنید'}</b><span>{payload.ready?'پرامپت نهایی شامل Cross-check داده‌ها، Packing، Dmax، گلوگاه آرماتور، ریسک پل‌زدگی و برنامه Trial Mix است.':'برای جلوگیری از تحلیل ناقص، پرونده نهایی پس از رسیدن تراکم به ۱۰۰٪ فعال می‌شود.'}</span></div><strong>{Math.round(props.compaction.progress*100)}٪</strong></div>
 <div className="ai-kpi-grid"><div><span>تراکم دانه‌ای</span><b>{payload.summary.packing}</b></div><div><span>فضای خالی</span><b>{payload.summary.voids}</b></div><div><span>Dmax نماینده</span><b>{payload.summary.dmax}</b></div><div><span>Bridge Risk</span><b>{payload.summary.bridge}</b></div></div>
 <div className={`ai-copilot-dossier risk-${payload.dossier.riskLevel==='زیاد'?'high':payload.dossier.riskLevel==='متوسط'?'medium':'low'}`}><div><span>سطح ریسک پرونده</span><strong>{payload.dossier.riskLevel}</strong></div><p><b>اقدام اولویت اول:</b> {payload.dossier.priority}</p><ol>{payload.dossier.trialMix.map((step,i)=><li key={i}>{step}</li>)}</ol></div>
 <div className="ai-review-warning">Copilot یک لایه پشتیبان تصمیم مهندسی است. پذیرش نهایی باید بر آزمایش معتبر، الزامات پروژه و استاندارد قابل اعمال متکی باشد؛ خروجی Packing، Compaction و Bridge Risk این نسخه مدل مهندسی/نماینده است.</div>
 <section className="ai-workflow"><div className="ai-step done"><i>۱</i><div><b>ورودی طرح</b><span>مصالح، نسبت‌ها و دانه‌بندی</span></div></div><div className={`ai-step ${payload.ready?'done':'active'}`}><i>۲</i><div><b>اجرای شبیه‌سازی</b><span>تراکم و ساختار دانه‌ای</span></div></div><div className={`ai-step ${payload.ready?'active':''}`}><i>۳</i><div><b>Engineering Copilot</b><span>پرونده، ریسک و Trial Mix</span></div></div></section>
 <div className="ai-section-head"><div><b>بسته داده مهندسی</b><span>داده عددی که همراه دستور تحلیل برای مدل هوش مصنوعی ارسال می‌شود</span></div><button onClick={()=>setExpanded(v=>!v)}>{expanded?'نمای خلاصه':'نمای کامل'}</button></div><div className={`ai-data-card ${expanded?'expanded':''}`}><pre>{payload.compactData}</pre></div>
 <label className="ai-prompt-label"><span><b>پرامپت Engineering Copilot</b><small>Cross-check، ماتریس ریسک، آرماتور/Dmax، اصلاحات و Trial Mix در ساختار پاسخ اجباری شده‌اند.</small></span><textarea readOnly value={payload.ready?payload.prompt:'پرونده و پرامپت نهایی پس از تکمیل شبیه‌سازی ساخته و فعال می‌شود.'}/></label>
 <div className="project-actions ai-actions"><button className="primary-action" disabled={!payload.ready} onClick={()=>copy('prompt')}>{copied==='prompt'?'✓ پرامپت کپی شد':'کپی پرونده کامل Copilot'}</button><button disabled={!payload.ready} onClick={()=>copy('data')}>{copied==='data'?'✓ داده‌ها کپی شد':'کپی فقط داده‌ها'}</button><button className="workflow-next" disabled={!payload.ready} onClick={props.onReport}>ادامه به گزارش مهندسی ←</button></div>
 <p className="ai-image-note"><b>تحلیل تصویری:</b> تصویر نمای سه‌بعدی، Heatmap، مقطع یا عکس آزمایشگاهی را همراه پرونده بدهید. Copilot موظف است شواهد بصری را از خروجی عددی تفکیک کند.</p><p className="ai-image-note ai-identity">{PRODUCT_IDENTITY.designer} • {PRODUCT_IDENTITY.phone} • {PRODUCT_IDENTITY.email} • {PRODUCT_IDENTITY.website}</p></div>;
}
