import { OrbitControls, PerspectiveCamera } from '@react-three/drei';
import { Canvas, useFrame } from '@react-three/fiber';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import * as THREE from 'three';
import type { MixAnalysis } from '../domain/mixDesign';
import type { ViewControls } from '../domain/viewControls';
import { defaultRebarNetwork, type RebarNetworkInput } from '../domain/rebarAnalysis';
import type { PackingResult } from '../engineering/packing';
import type { CompactionState } from '../engineering/compaction';
import type { ComplianceSummary } from '../engineering/referenceCompliance';
import { particleMatchesComplianceIssue } from '../engineering/referenceCompliance';
import { evaluateEngineeringHealth } from '../engineering/engineeringHealth';
import { particleBridgeRisk, analyzeRebarBridgeRisk, type BridgeParticleRisk } from '../engineering/rebarBridgeRisk';
import { LocalCompactionHeatmap3D } from './LocalCompactionHeatmap3D';
import { evaluateLocalCompactionHeatmap } from '../engineering/localCompactionHeatmap';
import { RebarLiveControls } from './RebarLiveControls';

interface Props { analysis: MixAnalysis; packing: PackingResult; compaction: CompactionState; view: ViewControls; compliance?: ComplianceSummary; }
type LayerKey = 'cement' | 'water' | 'silicaFume' | 'admixture' | 'air' | 'sand' | 'aggregate5to12' | 'aggregate12to25' | 'paste';
type LayerOpacity = Record<LayerKey, number>;
type LayerVisibility = Record<LayerKey, boolean>;
type ParticleRiskLevel = BridgeParticleRisk | 'compliance';

const COLORS: Record<Exclude<LayerKey, 'paste'>, string> = { cement:'#7f8790', water:'#2795d9', silicaFume:'#7557a8', admixture:'#35b7a0', air:'#f4f7fb', sand:'#d9b56f', aggregate5to12:'#d97b34', aggregate12to25:'#55677a' };
const LABELS: Record<LayerKey, string> = { cement:'سیمان', water:'آب', silicaFume:'میکروسیلیس', admixture:'افزودنی', air:'حباب هوا', sand:'ماسه', aggregate5to12:'نخودی ۴٫۷۵–۱۲', aggregate12to25:'بادامی ۱۲–۲۵', paste:'پس‌زمینه خمیر' };
const LAYER_ORDER: LayerKey[] = ['cement','water','silicaFume','admixture','air','sand','aggregate5to12','aggregate12to25','paste'];
const PHASE_ORDER: Record<string, number> = { aggregate12to25:0, aggregate5to12:1, sand:2 };
const DEFAULT_OPACITY: LayerOpacity = { cement:1, water:1, silicaFume:1, admixture:1, air:1, sand:1, aggregate5to12:1, aggregate12to25:1, paste:0.65 };

function initialVisibility(view: ViewControls): LayerVisibility { return { cement:view.phases.cement, water:view.phases.water, silicaFume:view.phases.silicaFume, admixture:view.phases.admixture, air:view.phases.air, sand:view.phases.sand, aggregate5to12:view.phases.aggregate5to12, aggregate12to25:view.phases.aggregate12to25, paste:view.phases.paste }; }
function sectionVisible(position:[number,number,number], view:ViewControls) { if (!view.sectionEnabled) return true; const i=view.sectionAxis==='x'?0:view.sectionAxis==='y'?1:2; return position[i] <= view.sectionPosition; }
function revealFactor(materialKey:string,index:number,total:number,progress:number) { if(progress<=0.02)return 0.14; const t=0.06+(PHASE_ORDER[materialKey]??2)*0.2+(index/Math.max(1,total))*0.18; return THREE.MathUtils.smoothstep(progress,t,Math.min(0.98,t+0.18)); }

function SectionPlane({view}:{view:ViewControls}) { if(!view.sectionEnabled)return null; const rotation:[number,number,number]=view.sectionAxis==='x'?[0,Math.PI/2,0]:view.sectionAxis==='y'?[Math.PI/2,0,0]:[0,0,0]; const position:[number,number,number]=view.sectionAxis==='x'?[view.sectionPosition,0,0]:view.sectionAxis==='y'?[0,view.sectionPosition,0]:[0,0,view.sectionPosition]; return <mesh position={position} rotation={rotation}><planeGeometry args={[1.05,1.05]}/><meshBasicMaterial color="#f28b2d" transparent opacity={0.15} side={THREE.DoubleSide} depthWrite={false}/></mesh>; }

function AnimatedParticle({particle,compaction,index,total,view,riskLevel,opacity}:{particle:PackingResult['particles'][number];compaction:CompactionState;index:number;total:number;view:ViewControls;riskLevel:ParticleRiskLevel;opacity:number}) {
 const ref=useRef<THREE.Mesh>(null); const materialRef=useRef<THREE.MeshStandardMaterial>(null);
 useFrame(({clock})=>{ if(!ref.current)return; const reveal=revealFactor(particle.materialKey,index,total,compaction.progress); const wave=Math.sin(clock.elapsedTime*34+index*0.73); const lateral=compaction.lateralVibration*wave; const settledY=-0.5+(particle.position[1]+0.5)*compaction.settlementFactor; const inletLift=(1-reveal)*(0.9+(index%11)*0.018); ref.current.position.set(particle.position[0]+lateral,settledY+inletLift,particle.position[2]-lateral*0.55); const scale=0.58+reveal*0.42; ref.current.scale.set(particle.scale[0]*scale,particle.scale[1]*scale,particle.scale[2]*scale); if(materialRef.current)materialRef.current.opacity=Math.max(0.04,reveal*opacity*(view.ghostMode?0.3:1)); });
 const base=COLORS[particle.materialKey as Exclude<LayerKey,'paste'>]??particle.color;
 const critical=riskLevel==='critical'||riskLevel==='compliance';
 const attention=riskLevel==='attention';
 const color=critical?'#ff3347':attention?'#ff8a2d':base;
 const emissive=critical?'#a60018':attention?'#8a3c00':'#000000';
 return <mesh ref={ref} visible={sectionVisible(particle.position,view)} rotation={particle.rotation}><icosahedronGeometry args={[particle.radius,1]}/><meshStandardMaterial ref={materialRef} color={color} emissive={emissive} emissiveIntensity={critical?0.95:attention?0.65:0} roughness={critical||attention?0.42:0.82} transparent opacity={compaction.progress<=0.02?0.14:opacity} depthWrite={opacity>0.65&&!view.ghostMode}/></mesh>;
}

function Particles({packing,compaction,view,compliance,visibility,opacity,rebarNetwork}:{packing:PackingResult;compaction:CompactionState;view:ViewControls;compliance?:ComplianceSummary;visibility:LayerVisibility;opacity:LayerOpacity;rebarNetwork:RebarNetworkInput}) {
 const issues=compliance?.issues??[];
 return <>{packing.particles.map((particle,index)=>{ const key=particle.materialKey as LayerKey; if(!visibility[key])return null; const complianceRisk=issues.some(issue=>particleMatchesComplianceIssue(particle.materialKey,particle.diameterMm,issue)); const bridgeRisk=(particle.materialKey==='aggregate5to12'||particle.materialKey==='aggregate12to25')?particleBridgeRisk(particle.diameterMm,rebarNetwork):'none'; const riskLevel:ParticleRiskLevel=complianceRisk?'compliance':bridgeRisk; return <AnimatedParticle key={particle.key} particle={particle} compaction={compaction} index={index} total={packing.particles.length} view={view} riskLevel={riskLevel} opacity={opacity[key]??1}/>; })}</>;
}

function representativePoints(count:number,seed:number){let state=seed>>>0;const random=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296};return Array.from({length:count},(_,key)=>({key,position:[-0.47+random()*0.94,-0.47+random()*0.94,-0.47+random()*0.94] as [number,number,number],scale:0.7+random()*0.6}));}
function RepresentativePhases({analysis,compaction,view,visibility,opacity}:{analysis:MixAnalysis;compaction:CompactionState;view:ViewControls;visibility:LayerVisibility;opacity:LayerOpacity}){const volume=(key:string)=>analysis.materials.find(m=>m.key===key)?.absoluteVolumeM3??0;const specs=useMemo(()=>[{key:'cement' as LayerKey,radius:0.009,count:Math.max(18,Math.min(90,Math.round(volume('cement')*480))),seed:13579},{key:'water' as LayerKey,radius:0.012,count:Math.max(14,Math.min(70,Math.round(volume('water')*300))),seed:97531},{key:'silicaFume' as LayerKey,radius:0.005,count:Math.max(8,Math.min(48,Math.round(volume('silicaFume')*900))),seed:44551},{key:'admixture' as LayerKey,radius:0.006,count:Math.max(5,Math.min(28,Math.round(volume('admixture')*1800))),seed:71327}],[analysis]);const reveal=compaction.progress<=0.02?0.1:THREE.MathUtils.smoothstep(compaction.progress,0.52,0.9);return <>{specs.map(spec=>visibility[spec.key]?representativePoints(spec.count,spec.seed).map(point=><mesh key={`${spec.key}-${point.key}`} visible={sectionVisible(point.position,view)} position={[point.position[0],-0.5+(point.position[1]+0.5)*Math.max(0.1,reveal),point.position[2]]} scale={point.scale}><sphereGeometry args={[spec.radius,8,6]}/><meshStandardMaterial color={COLORS[spec.key as Exclude<LayerKey,'paste'>]} roughness={spec.key==='water'?0.15:0.88} transparent opacity={Math.max(0.05,reveal*opacity[spec.key]*(view.ghostMode?0.25:spec.key==='water'?0.52:0.9))} depthWrite={spec.key!=='water'&&opacity[spec.key]>0.65}/></mesh>):null)}</>}
function AirVoids({analysis,view,visibility,opacity}:{analysis:MixAnalysis;view:ViewControls;visibility:LayerVisibility;opacity:LayerOpacity}){const count=Math.max(8,Math.min(42,Math.round(analysis.designedAirVolumeM3*900)));const points=useMemo(()=>representativePoints(count,818181),[count]);if(!visibility.air)return null;return <>{points.map(point=><mesh key={`air-${point.key}`} visible={sectionVisible(point.position,view)} position={point.position} scale={point.scale}><sphereGeometry args={[0.014,10,8]}/><meshPhysicalMaterial color={COLORS.air} transparent opacity={0.2*opacity.air*(view.ghostMode?0.45:1)} transmission={0.7} roughness={0.05} depthWrite={false}/></mesh>)}</>}
function PastePhase({analysis,compaction,visibility,opacity,view}:{analysis:MixAnalysis;compaction:CompactionState;visibility:LayerVisibility;opacity:LayerOpacity;view:ViewControls}){if(!visibility.paste)return null;const base=Math.cbrt(Math.min(0.92,Math.max(0.08,analysis.pasteVolumeM3)));const vertical=base*(0.97+compaction.progress*0.03);const reveal=compaction.progress<=0.02?0.1:THREE.MathUtils.smoothstep(compaction.progress,0.58,0.88);return <mesh scale={[base,vertical*reveal,base]} position={[0,-0.5+(vertical*reveal)/2,0]}><boxGeometry args={[1,1,1]}/><meshPhysicalMaterial color="#e6edf3" transparent opacity={0.045*opacity.paste*(view.ghostMode?0.55:1)} roughness={0.3} depthWrite={false}/></mesh>}

function MissingBandMarkers({compliance}:{compliance?:ComplianceSummary}){const missing=compliance?.issues.filter(i=>i.kind==='missing-sieve')??[];return <>{missing.slice(0,5).map((issue,index)=><mesh key={`${issue.materialKey}-${issue.sieveMm}`} position={[-0.43+index*0.08,0.43,0.43]}><sphereGeometry args={[0.018,12,8]}/><meshBasicMaterial color="#ffb020" transparent opacity={0.72} wireframe/></mesh>)}</>}

function BridgeZoneMarkers({packing,rebarNetwork}:{packing:PackingResult;rebarNetwork:RebarNetworkInput}){const bridge=useMemo(()=>analyzeRebarBridgeRisk(packing,rebarNetwork),[packing,rebarNetwork]);if(bridge.level==='low')return null;const critical=bridge.level==='high';return <group>{[-0.24,0,0.24].map((x,index)=><mesh key={index} position={[x,0,0]}><boxGeometry args={[0.14,0.86,0.035]}/><meshBasicMaterial color={critical?'#ff3047':'#ff8a2d'} transparent opacity={critical?0.11:0.065} wireframe={!critical} depthWrite={false}/></mesh>)}</group>}

function Scene({analysis,packing,compaction,view,compliance,visibility,opacity,heatmapVisible,rebarNetwork,rebarVisible}:Props&{visibility:LayerVisibility;opacity:LayerOpacity;heatmapVisible:boolean;rebarNetwork:RebarNetworkInput;rebarVisible:boolean}){const clippingPlanes=useMemo(()=>{if(!view.sectionEnabled)return[];const normal=view.sectionAxis==='x'?new THREE.Vector3(1,0,0):view.sectionAxis==='y'?new THREE.Vector3(0,1,0):new THREE.Vector3(0,0,1);return[new THREE.Plane(normal,-view.sectionPosition)]},[view.sectionAxis,view.sectionEnabled,view.sectionPosition]);return <><PerspectiveCamera makeDefault position={[1.45,1.05,1.55]} fov={42}/><ambientLight intensity={1.35}/><directionalLight position={[3,4,2]} intensity={2.5}/><pointLight position={[-2,1.5,1]} intensity={0.8} color="#3b82f6"/><PastePhase analysis={analysis} compaction={compaction} visibility={visibility} opacity={opacity} view={view}/><RepresentativePhases analysis={analysis} compaction={compaction} view={view} visibility={visibility} opacity={opacity}/><AirVoids analysis={analysis} view={view} visibility={visibility} opacity={opacity}/><Particles packing={packing} compaction={compaction} view={view} compliance={compliance} visibility={visibility} opacity={opacity} rebarNetwork={rebarNetwork}/><LocalCompactionHeatmap3D analysis={analysis} packing={packing} compaction={compaction} visible={heatmapVisible} rebarNetwork={rebarNetwork} rebarVisible={rebarVisible} rebarGhost={view.ghostMode}/><BridgeZoneMarkers packing={packing} rebarNetwork={rebarNetwork}/><MissingBandMarkers compliance={compliance}/><mesh><boxGeometry args={[1,1,1]}/><meshPhysicalMaterial clippingPlanes={clippingPlanes} transparent opacity={view.ghostMode?0.025:view.shellOpacity} roughness={0.08} transmission={0.48} depthWrite={false}/></mesh><SectionPlane view={view}/><lineSegments><edgesGeometry args={[new THREE.BoxGeometry(1,1,1)]}/><lineBasicMaterial color="#d9e4ee" transparent opacity={view.ghostMode?0.35:0.72}/></lineSegments><gridHelper args={[3,30,'#31557a','#13283e']} position={[0,-0.505,0]}/><OrbitControls makeDefault enableDamping dampingFactor={0.07} minDistance={1.1} maxDistance={5}/></>}

function layerVolumePercent(key:LayerKey,analysis:MixAnalysis){if(key==='air')return analysis.designedAirVolumeM3*100;if(key==='paste')return analysis.pasteVolumeM3*100;return analysis.materials.find(m=>m.key===key)?.volumePercent??0;}
export function ConcreteCube({analysis,packing,compaction,view,compliance}:Props){
 const[visibility,setVisibility]=useState<LayerVisibility>(()=>initialVisibility(view));const[opacity,setOpacity]=useState<LayerOpacity>(DEFAULT_OPACITY);const[solo,setSolo]=useState<LayerKey|null>(null);const[heatmapVisible,setHeatmapVisible]=useState(true);const[rebarVisible,setRebarVisible]=useState(true);const[rebarNetwork,setRebarNetwork]=useState<RebarNetworkInput>(defaultRebarNetwork);
 useEffect(()=>{if(!solo)setVisibility(initialVisibility(view))},[view.phases,solo]);
 const renderedVisibility=useMemo(()=>solo?Object.fromEntries(LAYER_ORDER.map(key=>[key,key===solo])) as LayerVisibility:visibility,[visibility,solo]);
 const health=useMemo(()=>evaluateEngineeringHealth(analysis,packing,compaction,compliance),[analysis,packing,compaction,compliance]);
 const heatmap=useMemo(()=>evaluateLocalCompactionHeatmap(analysis,packing,compaction,5,rebarNetwork),[analysis,packing,compaction,rebarNetwork]);
 const bridge=useMemo(()=>analyzeRebarBridgeRisk(packing,rebarNetwork),[packing,rebarNetwork]);
 const affected=new Set(compliance?.affectedMaterials??[]);const healthStyle={'--health':`${health.score}%`} as CSSProperties;const showAll=()=>{setSolo(null);setVisibility(Object.fromEntries(LAYER_ORDER.map(key=>[key,true])) as LayerVisibility)};const toggleSolo=(key:LayerKey)=>setSolo(current=>current===key?null:key);
 return <div className="viewport-canvas"><Canvas gl={{antialias:true,alpha:true,preserveDrawingBuffer:true}} onCreated={({gl})=>{gl.localClippingEnabled=true}}><Scene analysis={analysis} packing={packing} compaction={compaction} view={view} compliance={compliance} visibility={renderedVisibility} opacity={opacity} heatmapVisible={heatmapVisible} rebarNetwork={rebarNetwork} rebarVisible={rebarVisible}/></Canvas><div className={`health-orb ${health.level}`}><span>سلامت مهندسی</span><b>{health.score}</b><small>{health.labelFa}</small><i style={healthStyle}/></div><div className="heatmap-mini"><div><b>ریسک موضعی تراکم</b><span>{heatmap.meanRisk.toFixed(0)}/100</span></div><small>{heatmap.highRiskCells} سلول پرریسک • {heatmap.attentionCells} نیازمند توجه • {heatmap.rebarAffectedCells} متاثر از آرماتور</small><button onClick={()=>setHeatmapVisible(current=>!current)}>{heatmapVisible?'پنهان‌کردن نقشه':'نمایش نقشه'}</button></div><div className={`axis-label ${bridge.level==='high'?'risk':''}`} style={{top:12,right:326,bottom:'auto'}}>پل‌زدگی PSD • {bridge.score}/100 • {bridge.candidateSharePercent}٪ ذرات حساس</div><RebarLiveControls network={rebarNetwork} packing={packing} onChange={setRebarNetwork} visible={rebarVisible} onToggleVisible={()=>setRebarVisible(current=>!current)}/><div className="layers-panel"><div className="layers-head"><div><b>لایه‌های اجزای بتن</b><span>نمایش، Solo و شفافیت</span></div><button onClick={showAll}>همه</button></div>{LAYER_ORDER.map(key=>{const active=renderedVisibility[key];const color=key==='paste'?'#dbe5ed':affected.has(key as never)?'#ff3347':COLORS[key];return <div className={`layer-row ${active?'':'muted'}`} key={key}><button className="layer-eye" onClick={()=>{setSolo(null);setVisibility(current=>({...current,[key]:!current[key]}))}}>{active?'●':'○'}</button><button className={`layer-solo ${solo===key?'active':''}`} onClick={()=>toggleSolo(key)}>S</button><i className="layer-swatch" style={{background:color}}/><div className="layer-main"><div><span>{LABELS[key]}</span><b>{layerVolumePercent(key,analysis).toFixed(1)}٪</b></div><input aria-label={`شفافیت ${LABELS[key]}`} type="range" min="0.05" max="1" step="0.05" value={opacity[key]} onChange={event=>setOpacity(current=>({...current,[key]:Number(event.target.value)}))}/></div></div>})}</div><div className="health-breakdown"><div><span>تراکم</span><b>{health.packingScore}</b></div><div><span>حجم‌ها</span><b>{health.volumetricScore}</b></div><div><span>دانه‌بندی</span><b>{health.gradationScore}</b></div><div><span>اجرای تراکم</span><b>{health.compactionScore}</b></div></div><div className={`axis-label ${compliance?.issues.length?'risk':''}`}>۱٫۰۰۰ مترمکعب • {compaction.stage==='loose'?'آماده اجرای میکس':compaction.stage==='vibrating'?'در حال ورود و تراکم مصالح':'متراکم'}</div></div>;
}
